# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy application files
COPY main.py /app/

# Define environment variable
ENV MY_ENV_VAR=example_value

# Command to run the app
CMD ["python", "main.py"]
